# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  ## basic settings ##

  config.vm.box = "wheezy64"
  config.vm.box_url = "http://www.digitale-akademie.de/fileadmin/vagrantboxes/wheezy64.box"

  config.vm.hostname = "ibr-vagrantbox"
  config.vm.define "ibr-vagrantbox"

  config.vm.network :private_network, ip: "10.0.0.24"
  config.vm.network :forwarded_port, host: 8095, guest: 8095

  ## VM customization ##

  config.vm.provider :virtualbox do |vb|

	vb.name = "IBR Vagrantbox"

    vb.customize ["modifyvm", :id, "--memory", 2048]
    vb.customize ["modifyvm", :id, "--cpus", "2"]

  end

  ## provisioning ##

  config.vm.provision :shell, :path => "bootstrap.sh"

end
